### ISSUE TITLE
Add support for Search

### ISSUE THREAD

**Issue by simonplend** [Financial-Times/asari#31]
https://developer.github.com/v3/search/

**Comment by taktran** [comment]
I'm going to un-stale this issue, because I care now :)

A scenario that can occur, is that 100+ PRs get created accidentally, and then you want to know which ones they were (not that @Financial-Times/etg  ever make mistakes 😬). A simple way is just to search by the name using the issues API. This then allows you to close the issue with:

    <newline separated list of repo urls> | xargs -n1 ika close-project

Might be useful with https://github.com/Financial-Times/ika/issues/28 (but that is more about writing issues)

**Comment by sjparkinson** [comment]
I also think this could/should consider the work we've done in Financial-Times/ebi. Is there the potential to merge the projects? e.g. use the search API _and_ have a grep-ish contents search too.

**Comment by taktran** [comment]
Part of the reason for unarchiving this issue was needing to undo some PRs we accidentally created using [nori](https://github.com/Financial-Times/nori). Since  nori has greatly improved its undo capabilities since then, search is not as useful here.

+1 to having a good think about whether search could go into ebi 🦐
